### ISSUE TITLE
fossil is not mercurial

### ISSUE THREAD

**Issue by severak** [ianchanning/awesome-github-alternatives#1]
fossil is version control system by itself, it's not just interface to mercurial.

See https://en.wikipedia.org/wiki/Fossil_(software)

**Comment by ianchanning** [comment]
Yep, my bad I misread the [index.wiki](http://www.fossil-scm.org/index.html/doc/trunk/www/index.wiki):

>  In addition to doing distributed version control like Git and Mercurial

To imply that it also offered Git and Mercurial. I'll fix it.

**Comment by ianchanning** [comment]
Fixed with https://github.com/ianchanning/awesome-github-alternatives/commit/e6bb033b7c2809c7d7fbde298e8c98363f4bd802
