### ISSUE TITLE
This shares a lot with awesome-git

### ISSUE THREAD

**Issue by Jogai** [ianchanning/awesome-github-alternatives#3]
Why not contribute to https://github.com/dictcp/awesome-git this seems to mainly list a subset.

**Comment by ianchanning** [comment]
I guess the only a couple of issues with this:

1.  Findabliity. When I was searching for github alternatives, it didn't occur to me to search for generic 'Git' lists.
2. The Git list seems a bit more of a dumping ground of everything git, trying to find things in that list is hard. I've added tagging for the licence and language which makes it much easier when making decisions.

This list is for a specific use-case of an experienced git user wanting to move away from GitHub, I don't know if that fits with the use case of a beginner Git user wanting a set of general resources.

**Comment by ianchanning** [comment]
Closing as won't fix from above comment.
